BIN_PATH: /root/local/bin
ENV_PATH: /etc/profile.d
SVC_PATH: /usr/lib/systemd/system
SSL_PATH: /etc/kubernetes/ssl
ETCD_IPS: [10.28.50.41, 10.28.50.42, 10.28.50.43]
ETCD_NODES: 'etcd-host0=https://10.28.50.41:2380,etcd-host1=https://10.28.50.42:2380,etcd-host2=https://10.28.50.43:2380'
