- include_tasks: local.yml

- name: create kubelet config dir
  file: path={{ CONF_PATH }} state=directory
- name: sync conf dir
  synchronize: src={{ CONF_PATH }}/ dest={{ CONF_PATH }}/ delete=yes
- name: check install
  shell: kubelet --version
  register: result
  ignore_errors: True
- name: copy binary file
  copy: src={{ item }} dest={{ BIN_PATH }} mode=0755
  with_items:
  - kubelet
  - kube-proxy
  #- kubectl
  when: result|failed
- name: copy service file
  template: src={{ item }} dest={{ SVC_PATH }}
  with_items:
  - kubelet.service
  - kube-proxy.service
- name: create work dir
  file: path={{ item }} state=directory
  with_items:
  - /var/lib/kubelet
  - /var/lib/kube-proxy
- name: config service 
  service: name={{ item }} daemon_reload=yes enabled=yes state=restarted
  with_items:
  - kubelet
  - kube-proxy
