- name: copy addons yml  
  template: src={{ item }} dest={{ ADDON_PATH }}
  with_items:
  - calico-kube-controllers.yaml
  - kube-dns.yaml
- name: create addons  on master 
  shell: kubectl apply -f {{ ADDON_PATH }}/{{ item }}
  with_items:
  - calico-kube-controllers.yaml
  - kube-dns.yaml
