- name: create addon directory
  file: path={{ ADDON_PATH }} state=directory

- include_tasks: addons.yml
  when: NODE_NAME=='k8s-master01'

- include_tasks: authorize.yml
  when: NODE_NAME=='k8s-master01'
